<?php
/*
   Copyright 2016 idealo internet GmbH

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

?>
<?php if($this->isIdealoConfigComplete()) { ?>
    <div style="color:green;"><?php echo Mage::helper('idealo_direktkauf')->__('The configuration is complete!'); ?></div>
<?php } else { ?>
    <?php if($this->isIdealoTokenMissing()) { ?>
        <div style="color:red;"><?php echo Mage::helper('idealo_direktkauf')->__('Please enter an authorization-token!'); ?></div>
    <?php } elseif($this->isIdealoTokenIncorrect()) { ?>
        <div style="color:red;"><?php echo Mage::helper('idealo_direktkauf')->__('No connection could be established with this token!'); ?></div>
    <?php } elseif($this->isIdealoEmailMissing()) { ?>
        <div style="color:red;"><?php echo Mage::helper('idealo_direktkauf')->__('Please enter an email-address for error-mails!'); ?></div>
    <?php } ?>
<?php } ?>
