<?php
/*
   Copyright 2016 idealo internet GmbH

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

$aIdealoPaymentTypes = $this->getIdealoPaymentTypes();
$aShopPaymentTypes = $this->getShopPaymentTypes();
?>
<table>
    <?php foreach ($aIdealoPaymentTypes as $sKey => $sTitle) { ?>
        <tr>
            <td>
                <select name="<?php echo $this->getElement()->getName(); ?>[<?php echo $sKey; ?>]" style="width:222px;">
                    <option value=""><?php echo Mage::helper('adminhtml')->__('-- Please Select --'); ?></option>
                    <option value="0" <?php if($this->getValueByKey($sKey) == "0") echo 'selected'; ?>><?php echo Mage::helper('idealo_direktkauf')->__('Not used'); ?></option>
                    <?php foreach ($aShopPaymentTypes as $sShopPayKey => $sShopPayTitle) { ?>
                        <option value="<?php echo $sShopPayKey; ?>" <?php if($this->getValueByKey($sKey) == $sShopPayKey) echo 'selected'; ?>><?php echo $sShopPayTitle; ?></option>
                    <?php } ?>
                </select>
            </td>
            <td>
                <div style="margin-left:5px;width: 250px;"><?php echo $sTitle; ?></div>
            </td>
        </tr>
    <?php } ?>
</table>